require('./ready');
require('./guildMemberAdd');
require('./guildMemberUpdate');
require('./guildMemberRemove');
require('./presenceUpdate');
require('./voiceStateUpdate');
require('./messageCreate');
require('./messageReactionAdd');
require('./interactionCreate');
